# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

###############################################################################
###                           Base Configuration                            ###
###############################################################################

log-level = "{{ .BaseConfig.LogLevel }}"
validator-mnemonic = "{{ .BaseConfig.ValidatorMnemonic }}"
data-encryption-key-file = "{{ .BaseConfig.DataEncryptionKeyFile }}"

###############################################################################
###                         HTTP Configuration                              ###
###############################################################################

[http]

laddr = "{{ .HTTP.ListenAddr }}"
endpoint = "{{ .HTTP.Endpoint }}"

###############################################################################
###                         Panacea Configuration                           ###
###############################################################################

[panacea]

grpc-addr = "{{ .Panacea.GRPCAddr }}"

###############################################################################
###                         AWS S3 Configuration                            ###
###############################################################################

[aws-s3]

region = "{{ .AWSS3.Region }}"
bucket = "{{ .AWSS3.Bucket }}"
access-key-id = "{{ .AWSS3.AccessKeyID }}"
secret-access-key = "{{ .AWSS3.SecretAccessKey }}"

###############################################################################
###                         Enclave Configuration                           ###
###############################################################################

[enclave]

enable = {{ .Enclave.Enable }}
attestation-provider-addr = "{{ .Enclave.AttestationProviderAddr }}"
