# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

###############################################################################
###                           Base Configuration                            ###
###############################################################################

log-level = "info"
validator-mnemonic = "__VALIDATOR_MNEMONIC__"
data-encryption-key-file = ".dataval/config/data_encryption_key.sealed"

###############################################################################
###                         HTTP Configuration                              ###
###############################################################################

[http]

laddr = "0.0.0.0:8080"
endpoint = "https://my-validator.org"

###############################################################################
###                         Panacea Configuration                           ###
###############################################################################

[panacea]

grpc-addr = "panacea:9090"

###############################################################################
###                         AWS S3 Configuration                            ###
###############################################################################

[aws-s3]

region = "ap-northeast-2"
bucket = "data-market-test"
access-key-id = "__AWS_S3_ACCESS_KEY_ID__"
secret-access-key = "__AWS_S3_SECRET_ACCESS_KEY__"

###############################################################################
###                         Enclave Configuration                           ###
###############################################################################

[enclave]

enable = false
attestation-provider-addr = ""

###############################################################################
###                  AuthenticationConfig Configuration                     ###
###############################################################################

[authentication]

expiration = "5s"
size = 50000