version: "3.9"
services:
  panacea:
    image: ghcr.io/medibloc/panacea-core:master
    ports:
      - "9090:9090"
    volumes:
      - .:/e2e
    entrypoint: ["sh", "-c"]
    command:
      - |
        panacead init node1 --chain-id testing
        cp /e2e/genesis.json ~/.panacea/config/genesis.json
        panacead start

  dataval:
    build: ..
    ports:
      - "8080:8080"
    environment:
      DATAVAL_HTTP_LADDR: "0.0.0.0:8080"
      DATAVAL_PANACEA_GRPC_ADDR: "panacea:9090"
      DATAVAL_VALIDATOR_MNEMONIC: "${DATAVAL_VALIDATOR_MNEMONIC}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    volumes:
      - .:/e2e
    depends_on:
      - panacea
    command: >
      /e2e/wait-for panacea:9090 -- datavald

  e2e-test:
    build:
      context: ..
      target: build-env
    environment:
      E2E_DATAVAL_ADDR: "dataval:8080"
    volumes:
      - .:/e2e
    depends_on:
      - dataval
    command: >
      /e2e/wait-for dataval:8080 -- go test -v -count=1 ./e2e
