name: E2E Tests

on:
  push:
    branches:    # only for pushes on main
      - main
  pull_request:  # for all PRs regardless of its base branch

jobs:

  e2e:
    runs-on: ubuntu-latest



    steps:
      - name: Run Panacea
        run: |
          docker run \
            -p 9090:9090 \
            -v ${{ github.workspace }}/e2e:/e2e \
            --health-cmd "/usr/bin/panacead status" \
            --health-interval 5s \
            --health-timeout 5s \
            --health-retries 10 \
            ghcr.io/medibloc/panacea-core:master \
            /bin/bash /e2e/init_panacea.sh

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2