name: E2E Tests

on:
  push:
    branches:    # only for pushes on main
      - main
  pull_request:  # for all PRs regardless of its base branch

jobs:

  e2e:
    runs-on: ubuntu-latest

    services:
      panacea:
        image: ghcr.io/medibloc/panacea-core:master
        ports:
          - 9090:9090
        volumes:
          - ${{ github.workspace }}/e2e/init_panacea.sh:/e2e/init_panacea.sh
        options: >-
          --entrypoint "/e2e/init_panacea.sh"
          --health-cmd "/usr/bin/panacead status"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2