name: E2E Tests

on:
  push:
    branches:    # only for pushes on main
      - main
  pull_request:  # for all PRs regardless of its base branch

jobs:

  e2e:
    runs-on: ubuntu-latest



    steps:
      - uses: actions/checkout@v2

      - name: Run Panacea
        run: |
          docker run -d \
            -p 9090:9090 \
            -v $(pwd)/e2e/init_panacea.sh:/e2e/init_panacea.sh \
            ghcr.io/medibloc/panacea-core:master \
            /bin/bash /e2e/init_panacea.sh
          e2e/wait-for localhost:9090 --timeout=10

